### ISSUE TITLE
Use Conventional Commits

### ISSUE THREAD

**Issue by denysdovhan** [spaceship-prompt/spaceship-flutter#2]
Hey @merikan, i've noticed this section doesn't have any releases. That is because you don't use [Conventional Commits]( https://conventionalcommits.org). These commits are automatically detected. CI will automatically resolves the next released version and publishes it.

**Comment by merikan** [comment]
Hi @denysdovhan I didn't know that, I will make sure to use that in the future. ☺️
How should I proceed? I read the documentation and the recommendation was to do a `rebase`. Do you want me to rebase and force push (branch rules probably forbids) or should add just push an empty feat-commit to trigger a release?

**Comment by denysdovhan** [comment]
I think we should add a note about conventional commits to our contributing guidelines.

In your case, i think it's okay to just add a feat commit triggering a release. Let's treat all the previous commits as WIP.

**Comment by merikan** [comment]
I did a release now 
I haven't used `Conventional Commits` or `cycjimmy/semantic-release-action` before so I had to do read up on it.

Yes, adding a note  would really help. Maybe like this?
## For maintainers

A few notes for current and future maintainers of Spaceship:

- The version, changelog and release notes are generated automatically based on commit history.
- This repository adheres to [semver](https://semver.org/), using [conventional commits](https://www.conventionalcommits.org/) via [semantic-release](https://github.com/semantic-release/semantic-release).

**Comment by denysdovhan** [comment]
Note added to all of the projects under Spaceship org. Also, would be useful to take advantage of using something like this action: https://github.com/amannn/action-semantic-pull-request
